[project]
version = "0.0.11" 
name = "indexweights"
description = "A set of tools to scrape and analyze the weights of indices."
requires-python = ">=3.7"
dependencies = [
  "selenium",
]

[build-system]
requires = ["setuptools>=62.0.0", "wheel"]
build-backend = "setuptools.build_meta"